spring:
      #数据源配置
   datasource:
     url: jdbc:mysql://localhost:3306/elites?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useAffectedRows=true
     username: sa
     password: qwe!23
     driver-class-name: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
   redis:
        # Redis服务器地址
      host: 127.0.0.1
        # Redis数据库索引（默认为0）
      database: 0
        # Redis服务器连接端口
      port: 6379
      password: 12345
        #连接超时时间（毫秒）
      timeout: 3600s
      lettuce:
        pool:
          max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-idle: 8    # 连接池中的最大空闲连接 默认 8
          min-idle: 0    # 连接池中的最小空闲连接 默认 0
          max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
mybatis:
  typeAliasesPackage: com.entity
   #mapperLocations: classpath:mapper/*.xml
